services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: apps
      POSTGRES_PASSWORD: qasw123
      POSTGRES_DB: document_approval
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - '5432'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: apps
      DB_PASSWORD: qasw123
      DB_NAME: document_approval
      GO111MODULE: 'on'
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    volumes:
      - ./migrations:/app/migrations
      - .:/app
    working_dir: /app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8080
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

volumes:
  postgres_data:
